
package Codes_with_UserInterfaces;
        /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Codes_with_UserInterfaces.ActivitySelectionCode.*;
import java.util.ArrayList;
import java.util.Random;
//import java.awt.PageAttributes.MediaType.B.ActivitySelectionCode;
/**
 *
 * @author wafaa
 */
public class ActivityGUI extends javax.swing.JFrame {
    int numActivity;
    int seed;
Job arr[];
int i=0;
public String SelectedJobs="";
    /**
     * Creates new form ActivityGUI
     */
    public ActivityGUI() {
        initComponents();
    }
   static public Job[] createArray(int n)
    { Job[]  arr = new Job[n];return arr;}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResultButton = new javax.swing.JButton();
        randomExperienceButton = new javax.swing.JButton();
        input_Jobs_number_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        StartTimeField = new javax.swing.JTextField();
        FinishTimeField = new javax.swing.JTextField();
        nextJobButotn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        inputJobsNumberButton = new javax.swing.JButton();
        jobs_number_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        seedText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        inputSeed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(400, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResultButton.setBackground(new java.awt.Color(0, 0, 0));
        ResultButton.setForeground(new java.awt.Color(255, 255, 255));
        ResultButton.setText("Result");
        ResultButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ResultButton.setEnabled(false);
        ResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ResultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 89, 30));

        randomExperienceButton.setBackground(new java.awt.Color(0, 153, 204));
        randomExperienceButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        randomExperienceButton.setForeground(new java.awt.Color(255, 255, 255));
        randomExperienceButton.setText("Result of Random Experience");
        randomExperienceButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        randomExperienceButton.setEnabled(false);
        randomExperienceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomExperienceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(randomExperienceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 190, 30));

        input_Jobs_number_label.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        input_Jobs_number_label.setForeground(new java.awt.Color(0, 153, 204));
        input_Jobs_number_label.setText("Enter number of jobs");
        getContentPane().add(input_Jobs_number_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, 35));

        jLabel2.setBackground(new java.awt.Color(0, 51, 153));
        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("Enter Jobs:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, 60));

        jLabel4.setText("Start Time");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel5.setText("Finish Time");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));
        getContentPane().add(StartTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 50, 40));
        getContentPane().add(FinishTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 50, 39));

        nextJobButotn.setBackground(new java.awt.Color(204, 255, 153));
        nextJobButotn.setText("input Job");
        nextJobButotn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nextJobButotn.setEnabled(false);
        nextJobButotn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextJobButotnActionPerformed(evt);
            }
        });
        getContentPane().add(nextJobButotn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setText("you can also get random experience, just input seed:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 480, 30));

        inputJobsNumberButton.setBackground(new java.awt.Color(102, 255, 255));
        inputJobsNumberButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        inputJobsNumberButton.setText("input");
        inputJobsNumberButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inputJobsNumberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJobsNumberButtonActionPerformed(evt);
            }
        });
        getContentPane().add(inputJobsNumberButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, 30));
        getContentPane().add(jobs_number_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 50, 40));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText(" seed :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 30));
        getContentPane().add(seedText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 60, 40));

        jButton1.setBackground(new java.awt.Color(204, 153, 255));
        jButton1.setText("<-- return to the main page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        inputSeed.setBackground(new java.awt.Color(153, 255, 255));
        inputSeed.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        inputSeed.setText("input");
        inputSeed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inputSeed.setEnabled(false);
        inputSeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSeedActionPerformed(evt);
            }
        });
        getContentPane().add(inputSeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 50, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputJobsNumberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJobsNumberButtonActionPerformed

        numActivity=Integer.parseInt(jobs_number_field.getText().strip());
       
       arr=createArray(numActivity);
        
       
      // jobs_number_field.setText("");
        jobs_number_field.setEnabled(false);
        nextJobButotn.setEnabled(true);
       inputJobsNumberButton.setEnabled(false);
        inputSeed.setEnabled(true);

    }//GEN-LAST:event_inputJobsNumberButtonActionPerformed

    private void nextJobButotnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextJobButotnActionPerformed
        if(i<numActivity){
           int s=Integer.parseInt(StartTimeField.getText());
            int f=Integer.parseInt(FinishTimeField.getText());
       arr[i]=new Job(s,f);
        }
 if(i>=numActivity-1){
            nextJobButotn.setEnabled(false); nextJobButotn.setText("click Result Button");
            ResultButton.setEnabled(true);}
      i+=1;
      
        
         StartTimeField.setText("");
       FinishTimeField.setText("");
            
    }//GEN-LAST:event_nextJobButotnActionPerformed

    private void ResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultButtonActionPerformed
       
        ArrayList<Job> result=  ActivitySelectionCode.MaxActivities(arr,numActivity);
        
        for(int k=0;k<result.size();k++){
            SelectedJobs=SelectedJobs+'('+Integer.toString(result.get(k).start)+','+Integer.toString(result.get(k).finish)+')'+"\n";}

        
        ResultGUI resultActivity=new ResultGUI();
        resultActivity.setResult("selected Avticities\n"+SelectedJobs);
        resultActivity.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ResultButtonActionPerformed

    private void randomExperienceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomExperienceButtonActionPerformed
     Random r=new Random();
     String RandomInput="Random Activities are:\n";
     
     Job[]  randomActivities = new Job[numActivity];
     for(int i=0;i<numActivity;i++){
         int start=r.nextInt(seed/2);
         int finish=r.nextInt(seed)+start+1;
         randomActivities[i]=new Job(start,finish);
         
     }
      for(Job item:randomActivities)
          RandomInput+="("+item.start+","+item.finish+")\n";
     
       ArrayList<Job> result=  ActivitySelectionCode.MaxActivities(randomActivities,numActivity);
        
        for(int k=0;k<result.size();k++){
            SelectedJobs=SelectedJobs+'('+Integer.toString(result.get(k).start)+','+Integer.toString(result.get(k).finish)+')'+"\n";}

        
        ResultGUI resultActivity=new ResultGUI();
        resultActivity.setResult(RandomInput+"selected Avticities\n"+SelectedJobs);
        resultActivity.setVisible(true);
        this.setVisible(false);
    
               
    }//GEN-LAST:event_randomExperienceButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainGUI main=new MainGUI();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputSeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSeedActionPerformed
 seed=Integer.parseInt(seedText.getText().strip());  
 randomExperienceButton.setEnabled(true);
 seedText.setEnabled(false);
 inputSeed.setEnabled(false);
 // TODO add your handling code here:
    }//GEN-LAST:event_inputSeedActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActivityGUI().setVisible(true);
                
                
            }
        });
        
                
                   

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FinishTimeField;
    private javax.swing.JButton ResultButton;
    private javax.swing.JTextField StartTimeField;
    private javax.swing.JButton inputJobsNumberButton;
    private javax.swing.JButton inputSeed;
    private javax.swing.JLabel input_Jobs_number_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jobs_number_field;
    private javax.swing.JButton nextJobButotn;
    private javax.swing.JButton randomExperienceButton;
    private javax.swing.JTextField seedText;
    // End of variables declaration//GEN-END:variables

   
}
