/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Codes_with_UserInterfaces;
import Codes_with_UserInterfaces.MakespanCode;
import java.util.ArrayList;
import java.util.Collections;
import Codes_with_UserInterfaces.ResultGUI;
import java.util.Random;
/**
 *
 * @author wafaa
 */
public class MakespanGUI extends javax.swing.JFrame {
int machinesNum;
int jobsNum;
int i=0;
  ArrayList<Integer> jobsArray= new  ArrayList<Integer>();
   ArrayList<Integer> machinesArray= new  ArrayList<Integer>() ;
  String result;
  int seed=100;
    /**
     * Creates new form Makespan
     */
    public MakespanGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RandomExperience = new javax.swing.JButton();
        JobsNumText = new javax.swing.JTextField();
        MachinesNumButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JobNumText = new javax.swing.JTextField();
        nextJobButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        MachinesNumText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jobNumButton = new javax.swing.JButton();
        seedText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ResultButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        seedButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(102, 102, 102));
        setLocation(new java.awt.Point(400, 200));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RandomExperience.setBackground(new java.awt.Color(0, 153, 204));
        RandomExperience.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RandomExperience.setForeground(new java.awt.Color(255, 255, 255));
        RandomExperience.setText("Result of Random Experience");
        RandomExperience.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RandomExperience.setEnabled(false);
        RandomExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomExperienceActionPerformed(evt);
            }
        });
        getContentPane().add(RandomExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 220, 34));

        JobsNumText.setText(" ");
        getContentPane().add(JobsNumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 50, 40));

        MachinesNumButton.setBackground(new java.awt.Color(102, 255, 255));
        MachinesNumButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        MachinesNumButton.setText("input");
        MachinesNumButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MachinesNumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MachinesNumButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MachinesNumButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 60, 30));

        jLabel2.setBackground(new java.awt.Color(0, 51, 153));
        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Enter Jobs:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 120, 40));

        jLabel4.setText("length of job");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 80, -1));
        getContentPane().add(JobNumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 50, 40));

        nextJobButton.setBackground(new java.awt.Color(204, 255, 153));
        nextJobButton.setText("input Job");
        nextJobButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nextJobButton.setEnabled(false);
        nextJobButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextJobButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextJobButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Enter number of Jobs:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 250, 30));

        MachinesNumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MachinesNumTextActionPerformed(evt);
            }
        });
        getContentPane().add(MachinesNumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 50, 40));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setText("you can also test algorithm by Random values,input seed:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 420, 30));

        jobNumButton.setBackground(new java.awt.Color(102, 255, 255));
        jobNumButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jobNumButton.setText("input");
        jobNumButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jobNumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobNumButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jobNumButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 60, 30));
        getContentPane().add(seedText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 50, 40));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText(" seed:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 40, 30));

        jButton1.setBackground(new java.awt.Color(204, 153, 255));
        jButton1.setText("<-- return to the main page");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, -1));

        ResultButton.setBackground(new java.awt.Color(0, 0, 0));
        ResultButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ResultButton.setForeground(new java.awt.Color(255, 255, 255));
        ResultButton.setText("Result");
        ResultButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ResultButton.setEnabled(false);
        ResultButton.setFocusPainted(false);
        ResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ResultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 80, 50));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("Enter number of Machines:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 30));

        seedButton.setBackground(new java.awt.Color(102, 255, 255));
        seedButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        seedButton.setText("input");
        seedButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        seedButton.setEnabled(false);
        seedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seedButtonActionPerformed(evt);
            }
        });
        getContentPane().add(seedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 60, 30));

        setBounds(0, 0, 523, 360);
    }// </editor-fold>//GEN-END:initComponents

    private void MachinesNumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MachinesNumButtonActionPerformed
      String s=MachinesNumText.getText();
              machinesNum=Integer.parseInt(s.strip());
               for(int i=0;i<machinesNum;i++) 
        	machinesArray.add(0);
           //   MachinesNumText.setText("");
              MachinesNumText.setEnabled(false);
              MachinesNumButton.setEnabled(false);
    }//GEN-LAST:event_MachinesNumButtonActionPerformed

    private void jobNumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobNumButtonActionPerformed
    jobsNum=Integer.parseInt(JobsNumText.getText().strip()); 
    JobsNumText.setEnabled(false);
          jobNumButton.setEnabled(false);
          nextJobButton.setEnabled(true);
          seedButton.setEnabled(true);
    }//GEN-LAST:event_jobNumButtonActionPerformed

    private void nextJobButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextJobButtonActionPerformed
     
        jobsArray.add(Integer.parseInt(JobNumText.getText().strip()));
         if(i<jobsNum-1){
     
       JobNumText.setText("");
      }
         if(i>=jobsNum-1){
          nextJobButton.setEnabled(false); 
          JobNumText.setEnabled(false);
         ResultButton.setEnabled(true);
         nextJobButton.setText("click on Result");
      } 
         i++;  
    }//GEN-LAST:event_nextJobButtonActionPerformed

    private void RandomExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomExperienceActionPerformed
     String randomInput="Input Activities are:\n";
        Random r=new Random();
      
       for(int i=0;i<jobsNum;i++) {
              jobsArray.add(r.nextInt(seed));}
          Collections.sort(jobsArray);
          Collections.reverse(jobsArray);
          for(int j=0;j<jobsNum;j++) {
              machinesArray.set(0,jobsArray.get(j)+machinesArray.get(0));
              Collections.sort(machinesArray);
           }
   
     for(int i=0;i<jobsNum;i++){
        randomInput+=Integer.toString(jobsArray.get(i))+"\n" ;
     }
    result=Integer.toString(machinesArray.get(machinesNum-1));
    ResultGUI resultMakespan=new ResultGUI();
    resultMakespan.setResult( randomInput+"Makespan is\n"+result);
    resultMakespan.setVisible(true);   
      this.setVisible(false);
        
       
    }//GEN-LAST:event_RandomExperienceActionPerformed

    private void MachinesNumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MachinesNumTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MachinesNumTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainGUI main=new MainGUI();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultButtonActionPerformed
      for(int j=0;j<jobsNum;j++) {
   Collections.sort(jobsArray);
   
   machinesArray.set(0,jobsArray.get(jobsNum-1)+machinesArray.get(0));
   jobsArray.set(jobsNum-1, -100);  
      Collections.sort(machinesArray);}
result=Integer.toString(machinesArray.get(machinesNum-1));
 ResultGUI resultMakespan=new ResultGUI();
        resultMakespan.setResult("Makespan is :\n"+result);
        // resultMakespan.setLast(this);
        resultMakespan.setVisible(true);
this.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_ResultButtonActionPerformed

    private void seedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seedButtonActionPerformed
        seed=Integer.parseInt(seedText.getText().strip());   
            RandomExperience.setEnabled(true);// TODO add your handling code here:
            seedText.setEnabled(false);
            seedButton.setEnabled(false);
    }//GEN-LAST:event_seedButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakespanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakespanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakespanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakespanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakespanGUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JobNumText;
    private javax.swing.JTextField JobsNumText;
    private javax.swing.JButton MachinesNumButton;
    private javax.swing.JTextField MachinesNumText;
    private javax.swing.JButton RandomExperience;
    private javax.swing.JButton ResultButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jobNumButton;
    private javax.swing.JButton nextJobButton;
    private javax.swing.JButton seedButton;
    private javax.swing.JTextField seedText;
    // End of variables declaration//GEN-END:variables
}
