/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Codes_with_UserInterfaces;

import java.util.ArrayList;
import java.util.List;
import Codes_with_UserInterfaces.weightedActivityCode.Job;
import Codes_with_UserInterfaces.weightedActivityCode.*;

import java.util.Random;
/**
/**
 *
 * @author wafaa
 */
public class weightedActivityGUI extends javax.swing.JFrame {
List<Job> jobs=new ArrayList<Job>();
int numActivity;
int i=0;
String result="";

ArrayList<String> selectedJobs=new ArrayList<String>();
 int seed=10;
    /**
     * Creates new form weightedActivity
     */
    public weightedActivityGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        startTimeText = new javax.swing.JTextField();
        finishTimeText = new javax.swing.JTextField();
        weightText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jobsNumText = new javax.swing.JTextField();
        jobsNumButton = new javax.swing.JButton();
        nextJobButton = new javax.swing.JButton();
        resultButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        seedText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        randomResult = new javax.swing.JButton();
        inptSeed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 153, 255));
        jButton1.setText("<-- return to the main page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Enter number of jobs");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 220, 35));

        jLabel1.setBackground(new java.awt.Color(0, 51, 153));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Enter Jobs:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 60));
        getContentPane().add(startTimeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 50, 40));
        getContentPane().add(finishTimeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 50, 39));
        getContentPane().add(weightText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 50, 40));

        jLabel2.setText("Start Time");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setText("Finish Time");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel7.setText("Weight");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 60, -1));

        jobsNumText.setText(" ");
        getContentPane().add(jobsNumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 50, 40));

        jobsNumButton.setBackground(new java.awt.Color(102, 255, 255));
        jobsNumButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jobsNumButton.setText("input");
        jobsNumButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jobsNumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobsNumButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jobsNumButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 50, 30));

        nextJobButton.setBackground(new java.awt.Color(204, 255, 153));
        nextJobButton.setText("input Job");
        nextJobButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nextJobButton.setEnabled(false);
        nextJobButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextJobButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextJobButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 80, -1));

        resultButton.setBackground(new java.awt.Color(0, 0, 0));
        resultButton.setForeground(new java.awt.Color(255, 255, 255));
        resultButton.setText("Result");
        resultButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resultButton.setEnabled(false);
        resultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 100, 30));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setText("you can also get random experience just input the seed");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 510, 30));
        getContentPane().add(seedText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 50, 50));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Seed:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        randomResult.setBackground(new java.awt.Color(0, 102, 204));
        randomResult.setForeground(new java.awt.Color(255, 255, 255));
        randomResult.setText("Go to the result");
        randomResult.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        randomResult.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        randomResult.setEnabled(false);
        randomResult.setFocusPainted(false);
        randomResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomResultActionPerformed(evt);
            }
        });
        getContentPane().add(randomResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 170, 40));

        inptSeed.setBackground(new java.awt.Color(102, 255, 255));
        inptSeed.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        inptSeed.setText("input ");
        inptSeed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inptSeed.setEnabled(false);
        inptSeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inptSeedActionPerformed(evt);
            }
        });
        getContentPane().add(inptSeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 50, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainGUI main=new MainGUI();
        main.setVisible(true);
        //this.getDefaultCloseOperation();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jobsNumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobsNumButtonActionPerformed
        numActivity=Integer.parseInt(jobsNumText.getText().strip());

        // jobsNumText.setText("");
        jobsNumText.setEnabled(false);
        jobsNumButton.setEnabled(false);
        nextJobButton.setEnabled(true);
        inptSeed.setEnabled(true);
    }//GEN-LAST:event_jobsNumButtonActionPerformed

    private void nextJobButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextJobButtonActionPerformed
        if (i<numActivity){
            int start=Integer.parseInt(startTimeText.getText().strip());
            int finish=Integer.parseInt(finishTimeText.getText().strip());
            int profit=Integer.parseInt(weightText.getText().strip());
            jobs.add(new Job(start,finish,profit));

            if (i>numActivity-2){
                nextJobButton.setText("click Result");
                nextJobButton.setEnabled(false);
                resultButton.setEnabled(true);
            }
           
             i++;
            startTimeText.setText("");
            finishTimeText.setText("");
            weightText.setText("");

        }
    }//GEN-LAST:event_nextJobButtonActionPerformed

    private void resultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultButtonActionPerformed
        int n=numActivity;
        int[] check= new int[n];
        int x=  weightedActivityCode.findMaxProfit(jobs,check);
        result=Integer.toString(x);

        String SelectedJobsString="";
        int index=-1;
        
        for(int i=n-1;i>=0;i--)
        if (check[i]==1){
            index=i;
            break;
        }
     
        if(index!=-1){
         SelectedJobsString+=("("+jobs.get(index).start+","+jobs.get(index).finish+","+jobs.get(index).profit+")\n");
        for(int i=index;i>=0;i--)
        if(check[i]==1)
        if (jobs.get(i).finish<=jobs.get(index).start){
            SelectedJobsString+=("("+jobs.get(i).start+","+jobs.get(i).finish+","+jobs.get(i).profit+")\n");
            // sum+=jobs.get(i).profit;
            index=i;}
        }

        ResultGUI resultActivity=new ResultGUI();
        resultActivity.setResult("Max profit is\n"+result+"\nSelected Jobs are:\n"+SelectedJobsString);
        resultActivity.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_resultButtonActionPerformed

    private void randomResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomResultActionPerformed
        ArrayList<Job> randomEResult=new ArrayList();
        String arrayContent="Jobs of experience are :\n";
        //  int num=Integer.parseInt(jobsNumText.getText().strip());
        int[] check=new int[numActivity];
        List<Job> randomJobs = new ArrayList<Job>();
        Random r =new Random();
        
        for(int i=0;i<numActivity;i++){
            int start=r.nextInt(seed);
            int finish=r.nextInt(seed)+start+2;
            int profit=r.nextInt(seed)+10;
            randomJobs.add(new Job(start,finish,profit));
        }

        for (Job randomJob : randomJobs) {
            arrayContent = arrayContent+'(' + Integer.toString(randomJob.start) + ',' + Integer.toString(randomJob.finish) + ',' + Integer.toString(randomJob.profit) + ')' + "\n";
        }
        //       for(int i=0;i<num;i++){System.out.println(J[i].start+"\n");}
        int x=  weightedActivityCode.findMaxProfit(randomJobs,check);
        String SelectedJobsString="";
        result=Integer.toString(x);
        int index=-1;
        int n=numActivity;
        for(int i=n-1;i>=0;i--)
        if (check[i]==1){
            index=i;
            break;
        }
      
      if(index!=-1){
         SelectedJobsString+=("("+randomJobs.get(index).start+","+randomJobs.get(index).finish+","+randomJobs.get(index).profit+")\n");
        for(int i=index;i>=0;i--)
        if(check[i]==1)
        if ( randomJobs.get(i).finish<= randomJobs.get(index).start){
            SelectedJobsString+=("("+randomJobs.get(i).start+","+randomJobs.get(i).finish+","+randomJobs.get(i).profit+")\n");
            // sum+=jobs.get(i).profit;
            index=i;}
 }
        //        for (Job item : subSolution){
            //            SelectedJobsString=SelectedJobsString+'('+Integer.toString(item.start)+','+Integer.toString(item.finish)+','+Integer.toString(item.profit)+')'+"\n";}
        ResultGUI resultActivity=new ResultGUI();
        resultActivity.setResult(arrayContent+"Max profit is\n"+result+"\nSelected Jobs are:\n"+SelectedJobsString);
        resultActivity.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_randomResultActionPerformed

    private void inptSeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inptSeedActionPerformed
   seed=Integer.parseInt(seedText.getText().strip()); 
  randomResult.setEnabled(true);
   // TODO add your handling code here:
   seedText.setEnabled(false);
   inptSeed.setEnabled(false);
    }//GEN-LAST:event_inptSeedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(weightedActivityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(weightedActivityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(weightedActivityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(weightedActivityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new weightedActivityGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField finishTimeText;
    private javax.swing.JButton inptSeed;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jobsNumButton;
    private javax.swing.JTextField jobsNumText;
    private javax.swing.JButton nextJobButton;
    private javax.swing.JButton randomResult;
    private javax.swing.JButton resultButton;
    private javax.swing.JTextField seedText;
    private javax.swing.JTextField startTimeText;
    private javax.swing.JTextField weightText;
    // End of variables declaration//GEN-END:variables
}
